language: php

php:
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - mysql -e 'create database meelia_test;'

script: phpunit -c ./tests/phpunit.xml --bootstrap ./tests/bootstrap.php
